#!/bin/bash

source /volumes/"Install macOS Ventura"/values.conf

curl -s "https://raw.githubusercontent.com/actualaardvark/bashsetupscriptrepo/$gitupdatebranch/Additional%20Scripts/apps.conf" > /volumes/"$usbdevicename"/"Additional Scripts"/"apps.conf"

appdirectories=()
while IFS= read -r line; do
    appdirectories+=("$line")
done < "/volumes/"$usbdevicename"/password.txt"

declare -a installedapps=()

if [ $checklistii == "true" ]; then
    for ((i = 0; i < ${#appdirectories[@]}; i++)); do
        firstletter=${appdirectories[$i]:0:1}
        if [[ $firstletter != '#' ]]; then
            if [ -d "/Applications/${appdirectories[$i]}" ] || [ -d "/Applications/${appdirectories[$i]}.app" ]; then
                echo '[x] '"${appdirectories[$i]}"
            else
                echo '[ ] '"${appdirectories[$i]}"
            fi
        fi
    done
fi

totalapps=0
readyapps=0

for ((i = 0; i < ${#appdirectories[@]}; i++)); do
    firstletter=${appdirectories[$i]:0:1}
    if [[ $firstletter != '#' ]]; then
        if [ -d "/Applications/${appdirectories[$i]}" ] || [ -d "/Applications/${appdirectories[$i]}.app" ]; then
            readyapps=$(($readyapps + 1))
            totalapps=$(($totalapps + 1))
        else
            totalapps=$(($totalapps + 1))
        fi
    fi
done

echo "$readyapps"'/'"$totalapps"" Apps Installed"