#!/bin/bash

# Gets the users full name. Taken from Naming_Convention.sh
full_name=$(dscl . -read /Users/$(id -un 502) RealName | awk -F': ' '{print $2}')
# The first 3 letters of the user account's full name
userlevel=${full_name:0:3}

appdirectories=('Adobe Creative Cloud' "BitdefenderVirusScanner.app" "Garageband.app" "Keynote.app" 'Microsoft Excel.app' 'Microsoft PowerPoint.app' "Numbers.app" "Pages.app" "iMovie.app" 'Google Chrome.app' 'Microsoft OneNote.app')

installedapps=()

for ((i = 0; i < ${#appdirectories[@]}; i++)); do
    if [ -d "${appdirectories[$i]}" ]; then
        echo "${appdirectories[$i]} Installed"
        installedapps+=( 1 )
    else
        echo "${appdirectories[$i]} Not Installed"
        installedapps+=( 0 )
    fi
done
echo installedapps