#!/bin/bash
updatecheck(){
	# Downloads the latest version of the script from github
	curl https://raw.githubusercontent.com/actualaardvark/bashsetupscriptrepo/main/updateandrun > updateandrun
	# Compares the currently installed version with the new version
	oldupdater=$(shasum -a 256 /volumes/"Install macOS Ventura"/updateandrun)
	newupdater=$(shasum -a 256 updateandrun)
	oldupdaterhash=${oldupdater%% *}
	newupdaterhash=${newupdater%% *}
	# Replaces the old version with the new if the old copy is out of date
	if [ "$oldupdaterhash" != "$newupdaterhash" ]; then
		echo "Updater out of date"
		cat updateandrun > /volumes/"Install macOS Ventura"/updateandrun
		chmod +x /volumes/"install MacOS ventura"/updateandrun
		rm updateandrun
		osascript -e 'display notification "Updater out of date" with title "Restarting Script"'
		sh /volumes/"install MacOS ventura"/updateandrun
		exit 1
	else
		echo "Updater is on the latest version"
	fi
}

checklistrender () {
	# Loop through checklist items and display them with checkboxes
    clear
    for ((i=0; i<${#checklist[@]}; i++)); do
        if [[ ${checklist_status[$i]} -eq 1 ]]; then
            checkbox="[x]"
        else
            checkbox="[ ]"
        fi
        echo "$checkbox ${checklist[$i]}"
    done
}

usercheck () {
	if [ $(whoami) != "$requireduser" ]; then
		osascript -e 'display dialog "Login as _applecore to run this script"'
		exit 1
	fi
}

cat /volumes/"Install macOS ventura"/password.txt > password.txt

# Gets the users full name. Taken from Naming_Convention.sh
full_name=$(dscl . -read /Users/$(id -un 502) RealName | awk -F': ' '{print $2}')
# The first 3 letters of the user account's full name
userlevel = ${full_name:0:3}
# Define checklist items
checklist=("Installer Update Check" "Username Check" "Obtain Admin Permissions" "Network Name"  "Bonjour Name" "Device Name" "Script Wrap-Up")
# Sets the checked items
checklist_status=(0 0 0 0 0 0 0)
# Defines the user needed for the script to execute
requireduser="_applecore"

# Checks for updates
updatecheck
checklist_status=(1 0 0 0 0 0 0)
checklistrender

# Checks username
usercheck
checklist_status=(1 1 0 0 0 0 0)
checklistrender

# Obtains admin permission from user
echo $(cat "password.txt") | sudo -S -k echo ""
checklist_status=(1 1 1 0 0 0 0)
checklistrender

# Set HostName, ComputerName, and LocalHostName to the full name

echo $(cat "password.txt") | sudo -S -k scutil --set HostName "$full_name"
checklist_status=(1 1 1 1 0 0 0)
checklistrender

echo $(cat "password.txt") | sudo -S -k scutil --set LocalHostName "$full_name"
checklist_status=(1 1 1 1 1 0 0)
checklistrender

echo $(cat "password.txt") | sudo -S -k scutil --set ComputerName "$full_name"
checklist_status=(1 1 1 1 1 1 0)
checklistrender

# Renew user enrollment. Taken from user_enrollment.sh
echo $(cat "password.txt") | sudo -S -k profiles renew -type enrollment
checklist_status=(1 1 1 1 1 1 1)

checklistrender

echo $(cat "password.txt") | sudo -S -k dseditgroup -o edit -d $(id -un 502) -t user admin

rm password.txt