#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"

source values.conf

updateconfigfile(){
    if [ "$(curl $configupdateurl)" != "$(cat values.conf)" ]; then
		echo "Configuration file out of date"
		curl "$configupdateurl" > values.conf
		sh updateandrun
		exit 1
	else
		echo "Configuration file out of date"
	fi
}

obtainadminpassword(){
    if [ $passwordsource == "legacy" ]; then
        read -p "Enter Admin Password (You'll only need to do this once): " adminpassword
	    echo "$adminpassword" > password.txt
    fi
}

executeremotescript(){
    curl -s https://raw.githubusercontent.com/actualaardvark/bashsetupscriptrepo/$gitupdatebranch/Mac%20Guided%20Enrollment%20Script > "Mac Guided Enrollment Script"
    chmod +x "Mac Guided Enrollment Script"
    sh "Mac Guided Enrollment Script"
}

checkpasswordpresence(){
    if [ ! -f  password.txt ]; then
        obtainadminpassword
    else
    	executeremotescript
    	exit 1
    fi
}

checknetworkconnection(){
    if [[ $(ping -q -c1 $connectioncheckurl &>/dev/null && echo online || echo offline) == "offline" ]]; then
        echo "No Network Connection"
        exit 1
    fi
}

installappcheckscript(){
    mkdir "Additional Scripts"
    curl -s https://raw.githubusercontent.com/actualaardvark/bashsetupscriptrepo/$gitupdatebranch/Additional%20Scripts/App%20Install%20Inspector > "Additional Scripts"/"App Install Inspector"
    chmod +x "Additional Scripts"/"App Install Inspector"
}

if [ $connectioncheckenabled == "true" ]; then
    checknetworkconnection
fi

updateconfigfile

installappcheckscript

checkpasswordpresence

executeremotescript