#!/bin/bash

mkdir "$(dirname "${BASH_SOURCE[0]}")/../Docs"
cd "$(dirname "${BASH_SOURCE[0]}")/../Docs" || echo "Directory Access Failed" && exit 1

source values.conf
source update.sh

echo "Downloading Documentation"

downloadstructureimage(){
    curl -s https://raw.githubusercontent.com/actualaardvark/bashsetupscriptrepo/$gitupdatebranch/structure.conf > structure.conf
    filestodownload=()
    ishidden="false"
    while IFS= read -r line; do
        filestodownload+=("$line")
    done < "structure.conf"
    for ((i = 0; i < ${#filestodownload[@]}; i++)); do
        if [ ${filestodownload[$i]} = '#hide' ]; then
            ishidden="true"
        else
            downloadedfile=${filestodownload[$i]}
            if [ ! -f $downloadedfile ]; then
                if [[ $downloadedfile == *"/"* ]]; then
                    mkdir -p "${downloadedfile%/*}" && touch "$downloadedfile"
                else
                    touch "$downloadedfile"
                fi
            fi
            curl -s  https://raw.githubusercontent.com/actualaardvark/bashsetupscriptrepo/$gitupdatebranch/${filestodownload[$i]}.md > ${filestodownload[$i]}.md
        fi
    done
}