#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")/.."

source values.conf
source update.sh

# NMS<Asset Tag>-iLab<Color>-<Number>
# iLabRed-5-12759

arr=(${full_name//-/ })

number=$(echo ${arr[1]})

prefix="NMS"

mid=$(echo ${arr[0]})

asset=$(echo ${arr[2]})

final="$prefix$asset-$mid-$number"

real="$final"
echo $final

if [ $autopassword == "true" ]; then
	echo "$adminpassword" | sudo -S -k scutil --set ComputerName "$real"
else
	sudo scutil --set ComputerName "$real"
fi

if [ $autopassword == "true" ]; then
	echo "$adminpassword" | sudo -S -k scutil --set LocalHostName "$real"
else
	sudo scutil --set LocalHostName "$real"
fi

if [ $autopassword == "true" ]; then
	echo "$adminpassword" | sudo -S -k scutil --set HostName "$real"
else
	sudo scutil --set HostName "$real"
fi

if [ $autopassword == "true" ]; then
	echo "$adminpassword" | sudo -S -k scutil --set HostName "$real"
else
	sudo scutil --set HostName "$real"
fi

if [ $autopassword == "true" ]; then
	echo "$adminpassword" | sudo -S -k profiles renew -type enrollment
else
	sudo profiles renew -type enrollment
fi

if [ $autopassword == "true" ]; then
	echo "$adminpassword" | sudo -S -k dscl . -change /Users/$(id -un 502) RealName "$full_name" "$real"
else
	sudo dscl . -change /Users/tatrose RealName "$full_name" "$real"
fi