#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source values.conf
if [ $(echo $(cut -d ":" -f2 <<< $(system_profiler SPHardwareDataType | grep "Activation Lock Status:"))) = "Enabled" ]; then
    echo "Activation Lock Enabled. Use Legacy Install Method."
    exit 1
fi
cat password.conf | "Install macOS Ventura.app"/Contents/Resources/startosinstall --eraseinstall --agreetolicense --forcequitapps --newvolumename "Macintosh HD" --stdinpass