#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")" || echo "changing directory failed" && exit

source values.conf
source update.sh

if [ $(echo $(cut -d ":" -f2 <<< $(system_profiler SPHardwareDataType | grep "Activation Lock Status:"))) = "Enabled" ]; then
    echo "Activation Lock Enabled. Use Legacy Install Method."
    exit 1
fi
echo $adminpassword | Install\ macOS\ *.app/Contents/Resources/startosinstall --eraseinstall --agreetolicense --forcequitapps --newvolumename "Macintosh HD" --stdinpass