#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")/.." || echo "Directory Access Failed" && exit 1
source update.sh

read -p -r "Enter Network Name (Case-Sensitive): " netname

security find-generic-password -ga "$netname" | grep "Password:"